"""add floor placement_json

Revision ID: 9ff9e5f2c189
Revises: 3bc00de8c616
Create Date: 2026-07-13 01:25:13.502290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff9e5f2c189'
down_revision: Union[str, Sequence[str], None] = '3bc00de8c616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placement_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('floors', schema=None) as batch_op:
        batch_op.drop_column('placement_json')

    # ### end Alembic commands ###
